[default_config]
version = "0.10.0"
assembler = "gas"
instruction_set = "riscv"

[default_config.opts]
compiler = "zig"
compile_flags_txt = []
diagnostics = true
default_diagnostics = true

[[project]]
path = ""
version = "0.10.0"
assembler = "gas"
instruction_set = "riscv"

[project.opts]
compiler = "zig"
compile_flags_txt = []
diagnostics = true
default_diagnostics = false
